name: Bug report
description: Report errors or unexpected behavior.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        To make it easier for us to help you please enter detailed information below.
  - type: input
    attributes:
      label: LSPosed version
      description:  Only official LSPosed is supported. Don't use 'latest'. Specify actual version with 4 digits.
    validations:
      required: true
  - type: input
    attributes:
      label: Android version
    validations:
      required: true
  - type: input
    attributes:
      label: Custom OS version
    validations:
      required: true
  - type: checkboxes
    id: latest
    attributes:
      label: Version requirement
      options:
        - label: I am using latest debug CI version
          required: true
  - type: textarea
    attributes:
      label: Behavior
      description: Please describe the behavior when trying to screenshot.
      placeholder: The screenshot is black. / Cannot screenshot with error notification or toast.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Please provide the log zip saved from manager.
      placeholder: Upload logs zip by clicking the bar on the bottom.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Framework, Services, and Screenshot App
      description: Please upload your /system/framework/framework.jar, services.jar, and the screenshot app of your ROM(on AOSP, it's System UI), compressed in a zip file. If the file size is too large to fit GitHub's limit, please upload it to https://catbox.moe and provide the link.
      placeholder: Upload by clicking the bar on the bottom.
    validations:
      required: true
